export const companyTableData = [
  {
    company: "Adyen",
    ticker: "AFRM",
    vertical: "Payments",
    price: "$17.15",
    market: "$50.5",
    revenue: "49.0%",
    gross: "15.8%",
    ev: "6.3",
    ytd: "24.3%",
  },
  {
    company: "Affirm",
    ticker: "AFRM",
    vertical: "Lending",
    price: "$16.12",
    market: "$4.7",
    revenue: "32.0%",
    gross: "48.7%",
    ev: "4.9",
    ytd: "77.1%",
  },
  {
    company: "Alkami Technology",
    ticker: "ALKT",
    vertical: "B2B SaaS",
    price: "$16.27",
    market: "$1.5",
    revenue: "34.0%",
    gross: "53.0%",
    ev: "7.0",
    ytd: "10.0%",
  },
  {
    company: "AvidXchange",
    ticker: "AVDX",
    vertical: "Payments",
    price: "$10.21",
    market: "$2.0",
    revenue: "27.0%",
    gross: "61.5%",
    ev: "6.0",
    ytd: "10.5%",
  },
  {
    company: "Bakkt Holdings",
    ticker: "BKKT",
    vertical: "Wealth",
    price: "$1.32",
    market: "$0.1",
    revenue: "38%",
    gross: "--",
    ev: "0.4",
    ytd: "13.8%",
  },
  {
    company: "Virtu Financial Inc",
    ticker: "VIRT",
    vertical: "Wealth",
    price: "$17.0",
    market: "$3.1",
    revenue: "-22.0%",
    gross: "38.2%",
    ev: "2.6",
    ytd: "-17.8%",
  },
  {
    company: "Adyen",
    ticker: "AFRM",
    vertical: "Payments",
    price: "$17.15",
    market: "$50.5",
    revenue: "49.0%",
    gross: "15.8%",
    ev: "6.3",
    ytd: "24.3%",
  },
  {
    company: "Affirm",
    ticker: "AFRM",
    vertical: "Lending",
    price: "$16.12",
    market: "$4.7",
    revenue: "32.0%",
    gross: "48.7%",
    ev: "4.9",
    ytd: "77.1%",
  },
  {
    company: "Alkami Technology",
    ticker: "ALKT",
    vertical: "B2B SaaS",
    price: "$16.27",
    market: "$1.5",
    revenue: "34.0%",
    gross: "53.0%",
    ev: "7.0",
    ytd: "10.0%",
  },
  {
    company: "AvidXchange",
    ticker: "AVDX",
    vertical: "Payments",
    price: "$10.21",
    market: "$2.0",
    revenue: "27.0%",
    gross: "61.5%",
    ev: "6.0",
    ytd: "10.5%",
  },
];
